### ISSUE TITLE
Error when switching the order of execution of rules

### ISSUE THREAD

**Issue by CriGoT** [auth0-extensions/auth0-github-deploy#3]
When trying to update the order of execution of rules validation fails if a previous version of a rule used the same order of a different rule in the new deployment. 

An example of the change can be seen [here](https://github.com/CriGoT/github-source-control-integration/commit/eb642c3e0b9bdf1fa6d5e71a067aeeec66b5db36]) with the deployment failing 

```
2016-06-28T23:45:55.282Z - Updating rules...
2016-06-28T23:45:56.424Z - Existing rules: [
  {
    "id": "rul_TwHwyUjWKAGf6Cug",
    "name": "set-country",
    "stage": "login_success",
    "order": 1
  },
  {
    "id": "rul_WSRAraMQOsTbNWbl",
    "name": "log-to-console",
    "stage": "login_success",
    "order": 2
  },
  {
    "id": "rul_3lbUoWicsc07nUx0",
    "name": "require-complex-password",
    "stage": "user_registration",
    "order": 1
  }
]
2016-06-28T23:45:56.425Z - Processing rule 'log-to-console'
2016-06-28T23:45:56.425Z - Updating rule log-to-console (rul_WSRAraMQOsTbNWbl): {
  "enabled": true,
  "order": 1,
  "script": "function (user, context, callback) {\n  console.log(JSON.stringify({ user: user, context: context }, null, 2));\n  callback(null, user, context);\n}\n"
}
2016-06-28T23:45:56.426Z - Processing rule 'require-complex-password'
2016-06-28T23:45:56.426Z - Updating rule require-complex-password (rul_3lbUoWicsc07nUx0): {
  "enabled": false,
  "script": "function (ctx, cb) {\n\tif (!ctx.user.password || ctx.user.password.length < 8) {\n\t\treturn cb(new UnauthorizedError('Password does not match the password policy.'));\n\t};\n\n\tcb(null, ctx);\n}\n"
}
2016-06-28T23:45:56.428Z - Processing rule 'set-country'
2016-06-28T23:45:56.428Z - Updating rule set-country (rul_TwHwyUjWKAGf6Cug): {
  "enabled": false,
  "order": 2,
  "script": "function (user, context, callback) {\n\tif (context.request.geoip) {\n\t\tuser.country = context.request.geoip.country_name;\n\t}\n\tcallback(null, user, context);\n}\n"
}
2016-06-28T23:45:57.372Z - Error: A rule with the same order already exists
```

This error comes from the management API and because rules are updated one at a time with previous rules still being active.

The simple thign to do is delete all existing rules before creating the ones present in the repo since trying to solve order before updating the rules may be too complicated.

What do you think @sandrinodimattia?

**Comment by sandrinodm** [comment]
First we'll have docs soon that explain how you can deal with this: https://github.com/auth0/docs/commit/74bbc1c

Now about rollback. There are a few reasons why a deployment can fail:
1. Issue with GitHub (cannot download source, ...)
2. Validation issue (db connection does not exist, rule order collision)
3. Issue with API v2 (network connectivity, API v2 down, ..)

For 1 a rollback is not required. For 2 we can detect this before making any change to your Auth0 account. For 3 we could do a rollback, but the rollback itself can also fail.

Which is why I think instead of implementing the rollback logic (which can also fail), it might be better to validate the contents of the repo before we deploy anything:
1. Is the rule stage valid for all rules
2. Is the order valid for all rules (no collisions between rules or with what we have in Auth0)
3. Do all databases which we want to deploy scripts for exist in Auth0

Only if these items are validated we can start the deployment.

**Comment by CriGoT** [comment]
Agreed. Validation seems like a better way to go for now

**Comment by CriGoT** [comment]
Added validation in #5 to avoid this error
